# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class LogsMcpServer < Formula
  desc "IBM Cloud Logs MCP Server - Model Context Protocol server for IBM Cloud Logs"
  homepage "https://github.com/tareqmamari/logs-mcp-server"
  version "0.4.3"
  license "UNLICENSED"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tareqmamari/cloud-logs-mcp/releases/download/v0.4.3/cloud-logs-mcp_0.4.3_Darwin_x86_64.tar.gz"
      sha256 "2696ff4019f80090e2355de24454af7d0864c9d2fe8efe2ccab23f7f5bc94936"

      def install
        bin.install "logs-mcp-server"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tareqmamari/cloud-logs-mcp/releases/download/v0.4.3/cloud-logs-mcp_0.4.3_Darwin_arm64.tar.gz"
      sha256 "c117f082548314749d8ae540f22f3591babc7037838d51ccb8099c698422fcae"

      def install
        bin.install "logs-mcp-server"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/tareqmamari/cloud-logs-mcp/releases/download/v0.4.3/cloud-logs-mcp_0.4.3_Linux_x86_64.tar.gz"
      sha256 "17824f7f47ad355524f772493f9b73c29f3a396339ef95e3b9b6c0baa2e19e77"
      def install
        bin.install "logs-mcp-server"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tareqmamari/cloud-logs-mcp/releases/download/v0.4.3/cloud-logs-mcp_0.4.3_Linux_arm64.tar.gz"
      sha256 "725159fdf5e4ec3d959b0b85d9772e19e64f31e1e30013e8df6b22262b8da1e3"
      def install
        bin.install "logs-mcp-server"
      end
    end
  end

  def caveats
    <<~EOS
      To use logs-mcp-server, you need to configure:
        1. Get your IBM Cloud API key: https://cloud.ibm.com/iam/apikeys
        2. Set environment variables:
           export LOGS_API_KEY='your-api-key'
           export LOGS_SERVICE_URL='https://[instance-id].api.[region].logs.cloud.ibm.com'
           export LOGS_REGION='us-south'
        3. Configure in Claude Desktop

      For more information, see: https://github.com/tareqmamari/logs-mcp-server
    EOS
  end

  test do
    system "#{bin}/logs-mcp-server", "--version"
  end
end
