# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class LogsMcpServer < Formula
  desc "IBM Cloud Logs MCP Server - Model Context Protocol server for IBM Cloud Logs"
  homepage "https://github.com/tareqmamari/cloud-logs-mcp"
  version "0.11.0"
  license "UNLICENSED"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tareqmamari/cloud-logs-mcp/releases/download/v0.11.0/cloud-logs-mcp_0.11.0_Darwin_x86_64.tar.gz"
      sha256 "2d862e7081ebc9af36408c81c0c1fd80505005fbd4326670f387dd556e93ee82"

      define_method(:install) do
        bin.install "logs-mcp-server"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tareqmamari/cloud-logs-mcp/releases/download/v0.11.0/cloud-logs-mcp_0.11.0_Darwin_arm64.tar.gz"
      sha256 "7cf46ec6c831b5d6c0a74c0c20c6ec73d061b2afef9e716222b3d2a3dabb804a"

      define_method(:install) do
        bin.install "logs-mcp-server"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/tareqmamari/cloud-logs-mcp/releases/download/v0.11.0/cloud-logs-mcp_0.11.0_Linux_x86_64.tar.gz"
      sha256 "a3dc30918d4387fbd0fbb497c6ab900a793d79a24f98e9b37645d00385a08c84"
      define_method(:install) do
        bin.install "logs-mcp-server"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tareqmamari/cloud-logs-mcp/releases/download/v0.11.0/cloud-logs-mcp_0.11.0_Linux_arm64.tar.gz"
      sha256 "00e88c36635c56bd55e892f369da085d9e3d137b08a52e3ab053aae7bd5a1e9c"
      define_method(:install) do
        bin.install "logs-mcp-server"
      end
    end
  end

  def post_install
    # Auto-install embedded agent skills to user-level directory
    system "#{bin}/logs-mcp-server", "skills", "install"
  end

  def caveats
    <<~EOS
      To use logs-mcp-server, you need to configure:
        1. Get your IBM Cloud API key: https://cloud.ibm.com/iam/apikeys
        2. Set environment variables:
           export LOGS_API_KEY='your-api-key'
           export LOGS_SERVICE_URL='https://[instance-id].api.[region].logs.cloud.ibm.com'
        3. Configure in Claude Desktop

      Agent Skill (IBM Cloud Logs) has been installed to ~/.agents/skills/
      These work with Claude Code, Cursor, Gemini CLI, GitHub Copilot, and 30+ other agents.

      Manage skills:
        logs-mcp-server skills list               # list available skills
        logs-mcp-server skills install             # reinstall to ~/.agents/skills/
        logs-mcp-server skills install --project   # install to current project

      For more information, see: https://github.com/tareqmamari/cloud-logs-mcp
    EOS
  end

  test do
    system "#{bin}/logs-mcp-server", "--version"
  end
end
