# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class LogsMcpServer < Formula
  desc "IBM Cloud Logs MCP Server - Model Context Protocol server for IBM Cloud Logs"
  homepage "https://github.com/tareqmamari/logs-mcp-server"
  version "0.2.0"
  license "UNLICENSED"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tareqmamari/cloud-logs-mcp/releases/download/v0.2.0/cloud-logs-mcp_0.2.0_Darwin_x86_64.tar.gz"
      sha256 "cd7885198cbc15c3729f57bc95fe42a10333715f1398acc84b6bace8e3b50bad"

      def install
        bin.install "logs-mcp-server"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tareqmamari/cloud-logs-mcp/releases/download/v0.2.0/cloud-logs-mcp_0.2.0_Darwin_arm64.tar.gz"
      sha256 "c94a1978902ee8c629249dedf0b1d4d5693a18bad9dacbf8c33cbb0bc14d9899"

      def install
        bin.install "logs-mcp-server"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/tareqmamari/cloud-logs-mcp/releases/download/v0.2.0/cloud-logs-mcp_0.2.0_Linux_x86_64.tar.gz"
      sha256 "915343f4fbb40dafba6b5523d5a191c629863b042d05cd1f1886c7e9048928d0"
      def install
        bin.install "logs-mcp-server"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tareqmamari/cloud-logs-mcp/releases/download/v0.2.0/cloud-logs-mcp_0.2.0_Linux_arm64.tar.gz"
      sha256 "e929099d9d4ce893ec9246123ec347046ae06af39d3153ae9c82a1fea0f29b55"
      def install
        bin.install "logs-mcp-server"
      end
    end
  end

  def caveats
    <<~EOS
      To use logs-mcp-server, you need to configure:
        1. Get your IBM Cloud API key: https://cloud.ibm.com/iam/apikeys
        2. Set environment variables:
           export LOGS_API_KEY='your-api-key'
           export LOGS_SERVICE_URL='https://instance-id.api.region.logs.cloud.ibm.com'
           export LOGS_REGION='us-south'
        3. Configure in Claude Desktop

      For more information, see: https://github.com/tareqmamari/logs-mcp-server
    EOS
  end

  test do
    system "#{bin}/logs-mcp-server", "--version"
  end
end
